### ISSUE TITLE
[BUG] 0 jogadores

### ISSUE THREAD

**Issue by devico90** [lucaspaim/war-web#10]
Está sendo possível escolher 0 jogadores.
OBS.: Está sendo possível colocar qualquer valor inteiro na verdade. (ex.: -1)

https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-xfl1/v/t35.0-12/13717903_857214934409800_1440916078_o.png?oh=171785262b597f3cba7f06ff0e6bcec6&oe=578E907B&__gda__=1468971977_cf3e00724befff363251a12518bf65a2
https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-xla1/v/t35.0-12/13702344_857215081076452_1129459032_o.png?oh=b3f03739355c3aac74140aca3bd8cc32&oe=578E3B85&__gda__=1468948720_42478ceae6ce844a3ab3887fe3b119c9

**Comment by lucaspaim** [comment]
Foi feito um tratamento na branch "feature/issue=17"
