### ISSUE TITLE
[BUG] Exércitos sendo contados como territórios

### ISSUE THREAD

**Issue by devico90** [lucaspaim/war-web#12]
A contagem está sendo feita por exércitos, e não por territórios.

1) https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xaf1/v/t35.0-12/13702389_857216324409661_1881150564_o.png?oh=0f74bbd91e169573b6320b28e6ab2b75&oe=578E83FC&__gda__=1468945738_f0f5c173c42384ed9aaf3231a2dd3b95

2) https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-xal1/v/t35.0-12/13720700_857216211076339_2113060812_o.png?oh=0bd7902db92c3d6fe928cd1ffb760017&oe=578E92B7&__gda__=1468952672_d3d83f08c8c18c66516a72232b44e730

3) https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-xfa1/v/t35.0-12/13702287_857216451076315_1045222380_o.png?oh=2af4d46f837470b1052d4938feca0595&oe=578E4D6C&__gda__=1468951247_7446e04c7ff39fed3af134bd154b7cf4

**Comment by lucaspaim** [comment]
bug resolvido com a branch feature/issue=12
