### ISSUE TITLE
[BUG] Objetivo escrito errado

### ISSUE THREAD

**Issue by devico90** [lucaspaim/war-web#13]
Atual e errado: "Seu objetivo é conquistar 15 territórios e ocupar cada um com pelo menos 2 territorios"
Correto: Seu objetivo é conquistar 15 territórios e ocupar cada um com pelo menos 2 EXÉRCITOS.

https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-xfa1/v/t35.0-12/13702287_857216451076315_1045222380_o.png?oh=2af4d46f837470b1052d4938feca0595&oe=578E4D6C&__gda__=1468951247_7446e04c7ff39fed3af134bd154b7cf4

**Comment by lucaspaim** [comment]
Bug resolvido com a branch "feature/issue=13"
