### ISSUE TITLE
[BUG] Erro após defesa (bot) vencer uma batalha

### ISSUE THREAD

**Issue by devico90** [lucaspaim/war-web#15]
Ataquei com 3 e ele defendeu com 1.
A defesa ganhou e após clicar em continuar, disparou o erro.

1) https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xlt1/v/t35.0-12/13730591_857219224409371_1333059467_o.png?oh=df9f6f67edc4dd53cb762e5024f0341f&oe=578EB45E&__gda__=1468971896_ae171e840e1ef4592493ce8eab42d1cd

2) https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-xaf1/v/t35.0-12/13694216_857219437742683_289530255_o.png?oh=0d985142d406bd0f8b77fb73b21ae7f4&oe=578E9CC2&__gda__=1468963724_f6c8bf984573d0a62a22e827c0d218c2

**Comment by lucaspaim** [comment]
Bug resolvido com a branch "feature/issue=15"
