### ISSUE TITLE
[BUG] Cálculo de tropas para alocar

### ISSUE THREAD

**Issue by devico90** [lucaspaim/war-web#16]
O cálculo está sendo feito baseado na quantidade de exércitos, e não na quantidade de territórios.
No print a seguir, temos que eu possuo 16 territórios e 18 exércitos.
O "23" em "territórios" do jogador "iuhuih" não está fazendo sentido.
Dessa forma, ele está utilizando o 23 para o cálculo e permitindo que aloque 11 novas tropas, quando o certo seria alocar apenas 8 novas tropas, pois possuo 16 territórios.

https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-xlt1/v/t35.0-12/13718052_857221281075832_1477220085_o.png?oh=614bbb201b6f11984ee0134e72a7f39a&oe=578E31D5&__gda__=1468953203_918ade256ec37f2a9090bbbc70a734e2

**Comment by lucaspaim** [comment]
Bug corrigido com a branch "feature/issue=16"
