### ISSUE TITLE
[MELHORIA] Número máximo de jogadores

### ISSUE THREAD

**Issue by devico90** [lucaspaim/war-web#17]
Tratar o número máximo de jogadores para não abrir tela de erro.

https://scontent-gru2-1.xx.fbcdn.net/v/l/t35.0-12/13711442_857223427742284_1058832099_o.png?oh=065a749324006485d1c7fa3197697938&oe=578E5396

**Comment by lucaspaim** [comment]
Feita com a branch "feature/issue=17"
