### ISSUE TITLE
[BUG] território atacado não disponível

### ISSUE THREAD

**Issue by devico90** [lucaspaim/war-web#9]
Território Bayasabhad deveria estar habilitado para ser atacado.

https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xla1/v/t35.0-12/13720531_857213667743260_166986050_o.png?oh=1c32db0066e3d04880ce716f2253af55&oe=578E5457&__gda__=1468949578_fd52a85fcd493bdc7a61d3ed0126a134

**Comment by lucaspaim** [comment]
O mapemanto foi corrigido através da branch "feature/issue=9"
